version: "2"
services:
  redis:
    image: redis
    container_name: ip_cache
    expose:
      - 6379
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - redis
    environment:
      - REDIS_URL=redis://ip_cache
  mongo:
    image: mongo
    ports:
      - "27017:27017"